### ISSUE TITLE
Running WinUSB changes the sha1 checksum of the .iso file

### ISSUE THREAD

**Issue by AlexanderPuckhaber** [slacka/WinUSB#34] opened 2016-06-03 02:15 UTC
I ran WinUSB to install en_windows_7_home_premium_with_sp1_x64_dvd_u_676549.iso (sha1: 6c9058389c1e2e5122b7c933275f963edf1c07b9)
After running WinUSB, I checked the checksum again. This time, it was sha1: c1d94c9a1c8a2363c5fc032d244edaf69f8f51c0
I was unable to install windows from the .iso because it was missing drivers and couldn't select my drivers disk
The torrent I used was able to verify 99.9% of the .iso after I ran WinUSB, so it looks like a very small error.

**Comment by larsnystrom** [comment] 2016-06-16 20:01
I also had this problem:

```
cmp -l Win10_1511_2_Swedish_x64.iso Win10_1511_2_Swedish_x64.iso.second | gawk '{printf "%08X %02X %02X\n", $1, strtonum(0$2), strtonum(0$3)}'
00088805 31 58
00088809 B1 26
0008880A EB 9D
00088811 78 5C
00088812 10 1E
00088815 06 04
00088816 10 1A
00088817 15 17
00088818 32 20
00088819 22 28
0008881A 2F 00
0008881B 4E 00
0008881C 38 00
00088871 04 06
00088872 05 00
00088885 01 02
00088886 02 01
```

The first file is the the ISO I downloaded from Microsoft and used with WinUSB. The second one is the a copy of the same ISO before I used it with WinUSB. As you can see there are some differences.

It's a bit worrying that WinUSB tampers with the ISO.

**Comment by Lin-Buo-Ren** [comment] 2016-07-08 18:01
It's really interesting as WinUSB simplay mounted the ISO and copy all of it's contents to the target filesystem.  I'll look at it.

**Comment by Lin-Buo-Ren** [comment] 2016-07-08 18:39
Hi, I tried to reproduce the same issue with `sudo winusb --format 'Windows10_InsiderPreview_Client_x64_zh-tw_14295.1000.iso' /dev/loop0` but the checksum of the ISO file isn't changed, how do you run the WinUSB and which version you're using?

**Comment by larsnystrom** [comment] 2016-07-11 20:00
```
lars@zenbook:~$ apt-cache policy winusb
winusb:
  Installed: 1.0.11.1+git20160215-1~webupd8~trusty1
  Candidate: 1.0.11.1+git20160215-1~webupd8~trusty1
  Version table:
 *** 1.0.11.1+git20160215-1~webupd8~trusty1 0
        500 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

I used the CLI. I can't remember if I used `--install` or `--format`.

**Comment by Lin-Buo-Ren** [comment] 2016-07-20 01:26
@larsnystrom Please try the latest version from the PPA, we might need the exact issue reproduce instructions (including the same source image) as currently there's no trace in our code that may trigger this issue.

**Comment by larsnystrom** [comment] 2016-07-24 17:03
Here's a console transcript where I reproduced the issue with the latest version of winusb (the last command checks the version). Sorry about the parts in Swedish. The line `
mount: blockenhet /home/lars/Program/Windows 10/Win10_1511_2_Swedish_x64.iso är skrivskyddad, monterar som endast läsbar` means that the block device <iso path> is write-protected and mounted as read-only.

	lars@zenbook:Windows 10$ sha1sum Win10_1511_2_Swedish_x64.iso 
	d3747aa7aacf76645de9f763c718b631e395dba8  Win10_1511_2_Swedish_x64.iso
	lars@zenbook:Windows 10$ cp Win10_1511_2_Swedish_x64.iso Win10_1511_2_Swedish_x64.iso.bk
	lars@zenbook:Windows 10$ sudo winusb --format Win10_1511_2_Swedish_x64.iso /dev/sdc
	Formatting device...
	Wait 3 seconds for block device nodes to populate...
	mkfs.fat 3.0.26 (2014-03-07)
	mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
	Mounting...
	mount: blockenhet /home/lars/Program/Windows 10/Win10_1511_2_Swedish_x64.iso är skrivskyddad, monterar som endast läsbar
	Copying...
	Installing grub...
	Installing for i386-pc platform.
	Installation finished. No error reported.
	Installing grub.cfg...
	Exiting...
	Syncing...
	Cleaning...
	Unmounting and removing '/media/winusb_iso_1469378705_5459'...
	Unmounting and removing '/media/winusb_target_1469378705_5459'...
	lars@zenbook:Windows 10$ sha1sum Win10_1511_2_Swedish_x64.iso
	f1421750d7aef0ca15aecb7eee5a543e3a6aff60  Win10_1511_2_Swedish_x64.iso
	lars@zenbook:Windows 10$ cmp -l Win10_1511_2_Swedish_x64.iso Win10_1511_2_Swedish_x64.iso.bk | gawk '{printf "%08X %02X %02X\n", $1, strtonum(0$2), strtonum(0$3)}'
	00088805 3C 58
	00088809 1F 26
	0008880A 88 9D
	00088811 78 5C
	00088812 10 1E
	00088815 07 04
	00088816 18 1A
	00088817 12 17
	00088818 2D 20
	00088819 05 28
	0008881A 53 00
	0008881B 04 00
	0008881C 5C 00
	00088871 04 06
	00088872 05 00
	00088885 01 02
	00088886 02 01
	lars@zenbook:Windows 10$ apt-cache policy winusb
	winusb:
	  Installerad: 1.0.11.1+git20160722-1~webupd8~trusty0
	  Kandidat:    1.0.11.1+git20160722-1~webupd8~trusty0
	  Versionstabell:
	 *** 1.0.11.1+git20160722-1~webupd8~trusty0 0
	        500 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/ trusty/main amd64 Packages
	        100 /var/lib/dpkg/status

**Comment by Holzhaus** [comment] 2016-08-04 16:14
Strange. This might be some kind of kernel bug? Because if you look at the code there is absolutely nothing happening with the `isoPath` other than mounting. And the ISO is mounted read only, so changes should no be possible.

Can you manually mount the ISO any check if the checksum changes too?

```bash
mount -o loop -t udf,iso9660 "/path/to/image.iso" "/mnt/winiso"
```

**Comment by larsnystrom** [comment] 2016-08-13 18:58
Yep, seems like mount is doing something to the iso. Included `uname -a` in this transcript if you're interested.

	$ sha1sum Win10_1511_2_Swedish_x64.iso 
	d3747aa7aacf76645de9f763c718b631e395dba8  Win10_1511_2_Swedish_x64.iso
	$ sudo mount -o loop -t udf,iso9660 /home/lars/Program/Windows\ 10/Win10_1511_2_Swedish_x64.iso /mnt/winiso
	mount: blockenhet /home/lars/Program/Windows 10/Win10_1511_2_Swedish_x64.iso är skrivskyddad, monterar som endast läsbar
	$ sha1sum Win10_1511_2_Swedish_x64.iso
	ee6365d440c676ccd526ecbf6af524d6cdfecc2b  Win10_1511_2_Swedish_x64.iso
	$ sudo umount /mnt/winiso 
	$ sha1sum Win10_1511_2_Swedish_x64.iso
	ee6365d440c676ccd526ecbf6af524d6cdfecc2b  Win10_1511_2_Swedish_x64.iso
	$ uname -a
	Linux zenbook 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Holzhaus** [comment] 2016-08-14 08:31
You should probably file a bug report over at Canonical's bug tracker, since that seems to be a kernel issue.

**Comment by larsnystrom** [comment] 2016-08-14 19:48
Found this bug:
https://bugs.launchpad.net/ubuntu/+source/kernel-package/+bug/1277146

They suggest mounting the iso as read only with -o ro to avoid this behavior. I haven't tried that yet, so I'm not sure if it works, but if it does then maybe WinUSB can do that as well?

**Comment by Holzhaus** [comment] 2016-08-15 10:17
Strange, if was convices that WinUSB already mount it read-only. Turns out I was wrong. I'll file a PR.

**Comment by Lin-Buo-Ren** [comment] 2016-08-15 10:31
Hi, sorry for not responding in a timely manner.  I previously believe that this is a readonly process because the system log says so.  Thanks to @larsnystrom and @Holzhaus for finding out the actual issue is.

It seems that at least for UDF filesystem there's possibility for fs driver to mount it in read-write mode, in this case we really should add the ro flag to the mount command.

**Comment by Lin-Buo-Ren** [comment] 2016-08-15 16:55
According to the bug report this bug is fixed on Linux kernel 4.3 and later versions, as a workaround you could install a newer kernel

**Comment by Holzhaus** [comment] 2016-08-16 10:20
@larsnystrom Can you retest with latest upstream and close this bug report if the issue is resolved?

**Comment by larsnystrom** [comment] 2016-08-21 20:00
I'm sorry I've been so quiet. I think I screwed up my way of testing this by upgrading the kernel to 4.4. Ubuntu was nagging me on how my system wasn't getting any more security updates so I clicked the update button without thinking :|

I'll try the new version of winusb anyway when I get the time, hopefully this week.

**Comment by larsnystrom** [comment] 2016-09-18 09:51
I'm sorry, I won't have time to test this. I wouldn't be able to close this issue anyway, since I'm not the author.

Thank you for your work on WinUSB, it's a great tool.

**Comment by Lin-Buo-Ren** [comment] 2016-09-18 11:09
@AlexanderPuckhaber Would you try reproducing the bug with >4.3 Linux kernel?

**Comment by AlexanderPuckhaber** [comment] 2016-09-18 19:38
Sure. The checksum didn't change this time, using 4.4.0-36-generic on Ubuntu. I'll close this bug report.

**Closed** 2016-09-18 19:38 UTC
